name: Quarkus Pipeline Test Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo

  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: 'google.com.br'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy staging

  deploy-sandbox:
    runs-on: ubuntu-latest
    environment:
      name: sandbox
      url: 'google.com.br'
    needs: deploy-staging
    steps:
      - name: Run a one-line script
        run: echo Deploy Sandbox

  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'google.com.br'
    needs: deploy-sandbox
    steps:
      - name: Run a one-line script
        run: echo Deploy Production